#!/bin/bash
# Does the initial clone of all the cinnamon stuff

. buildorder


for k in $(seq 0 $((${#BUILDORDER[@]} - 1))); do
    if [ -d "${BUILDORDER[$k]}" ]; then
        echo "..............Diretório ${BUILDORDER[$k]} já existe, pulando clone."
        continue
    fi
    echo "..............Running git clone for ${BUILDORDER[$k]} upstream"
    git clone -o upstream ${REMOTES[$k]} ${BUILDORDER[$k]}/
done