#!/bin/bash

. buildorder

for dir in ${BUILDORDER[@]}; do
    echo "..............Running makepkg for $dir"
    cd $dir
    makepkg -s
    if [ $? != 0 ]; then
        echo "ERROR with $dir!"
        exit 1
    fi
    cd ..
done
