#!/bin/bash

. buildorder

for dir in ${BUILDORDER[@]}; do
    echo "..............Running pbuilder for $dir"
    cd $dir
    VERSION=$(dpkg-parsechangelog | sed -n "s/^Version: //p")
    cd ..
    # HACK: fix xapps
    dsc_basename="$(echo ${dir} | sed s/xapps/xapp/g)"
    sudo DIST=$1 pbuilder build ${dsc_basename}_$VERSION.dsc
    if [ $? != 0 ]; then
        echo "ERROR with $dir!"
        exit 1
    fi
done
